AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Synvya – Free service with terms acceptance tracking
  Records user signups and terms acceptance in S3

# ---------------------------------------------------------------------------
# Parameters
# ---------------------------------------------------------------------------
Parameters:
  S3BucketName:
    Type: String
    Default: synvya-user-records-prod
    Description: Name of the pre-existing S3 bucket that stores user signup records

  LambdaExecutionRoleArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/synvya/lambda-execution-role-arn"

# ---------------------------------------------------------------------------
# Resources
# ---------------------------------------------------------------------------
Resources:

# ---------------------------------------------------------------------------
# Execution role for all functions
# ---------------------------------------------------------------------------
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Retain
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: lambda.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub "arn:aws:s3:::${S3BucketName}/*"

# ---------------------------------------------------------------------------
# Lambda: record-terms-acceptance
# ---------------------------------------------------------------------------
  RecordTermsAcceptanceFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: synvya-record-terms-acceptance
      Runtime: nodejs20.x
      Handler: index.handler
      Role: !Ref LambdaExecutionRoleArn
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: lambda-functions/record-terms-acceptance.zip
      Environment:
        Variables:
          USER_RECORDS_BUCKET: !Ref S3BucketName
      Timeout: 30

  RecordTermsAcceptanceUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !GetAtt RecordTermsAcceptanceFunction.Arn
      AuthType: NONE

  RecordTermsAcceptanceUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref RecordTermsAcceptanceFunction
      Action: lambda:InvokeFunctionUrl
      Principal: "*"
      FunctionUrlAuthType: NONE

# ---------------------------------------------------------------------------
# Lambda: health-check
# ---------------------------------------------------------------------------
  HealthCheckFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: synvya-health-check
      Runtime: nodejs20.x
      Handler: index.handler
      Role: !Ref LambdaExecutionRoleArn
      Code:
        ZipFile: |
          export const handler = async (event, context) => {
              const method = event.requestContext.http.method;
              
              if (method === 'OPTIONS') {
                  return {
                      statusCode: 200,
                      headers: {
                          'Access-Control-Allow-Origin': '*',
                          'Access-Control-Allow-Headers': 'Content-Type',
                          'Access-Control-Allow-Methods': 'GET, OPTIONS',
                          'Access-Control-Max-Age': '86400'
                      },
                      body: ''
                  };
              }
              
              if (method !== 'GET') {
                  return {
                      statusCode: 405,
                      headers: { 'Access-Control-Allow-Origin': '*' },
                      body: JSON.stringify({ error: 'Method not allowed' })
                  };
              }
              
              return {
                  statusCode: 200,
                  headers: {
                      'Content-Type': 'application/json',
                      'Access-Control-Allow-Origin': '*'
                  },
                  body: JSON.stringify({
                      status: 'healthy',
                      environment: process.env.NODE_ENV || 'production',
                      timestamp: new Date().toISOString(),
                      message: 'Synvya serverless functions are operational',
                      runtime: 'aws-lambda'
                  })
              };
          };
      Timeout: 30

  HealthCheckUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !GetAtt HealthCheckFunction.Arn
      AuthType: NONE

  HealthCheckUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref HealthCheckFunction
      Action: lambda:InvokeFunctionUrl
      Principal: "*"
      FunctionUrlAuthType: NONE

# ---------------------------------------------------------------------------
# Outputs
# ---------------------------------------------------------------------------
Outputs:
  RecordTermsAcceptanceUrl:
    Description: URL for recording terms acceptance
    Value: !GetAtt RecordTermsAcceptanceUrl.FunctionUrl
    Export:
      Name: !Sub "${AWS::StackName}-RecordTermsAcceptanceUrl"

  HealthCheckUrl:
    Description: URL for health check endpoint
    Value: !GetAtt HealthCheckUrl.FunctionUrl
    Export:
      Name: !Sub "${AWS::StackName}-HealthCheckUrl"