version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - api

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/code
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://synvya:secret@db:5432/synvya
      - CORS_ORIGINS=["http://localhost:5173"]

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: synvya
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: synvya
    ports:
      - "5432:5432" # expose to host for local psql access
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
