[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  autoLaunch = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 