# =========================================================
# Deploy Synvya Client → S3 + CloudFront + Lambda Functions
# =========================================================
name: Deploy client.synvya.com

on:
  push:
    branches: [ main ]
  workflow_dispatch:        # allow manual "Run workflow" button

permissions:
  id-token: write      # <-- allows OIDC token
  contents: read       # <-- allows checkout

concurrency:                # never run two deploys in parallel
  group: deploy-client
  cancel-in-progress: true

env:
  NODE_VERSION: "18"
  BUILD_DIR: dist
  BUCKET_NAME: client-synvya-com               # ❶ S3 bucket
  DISTRIBUTION_ID: E3DPPDWMXK3MAD              # ❂ CloudFront ID
  AWS_REGION: us-east-1                        # ❸ Region for S3 + CLI
  LAMBDA_STACK_NAME: synvya-lambda-infrastructure
  LAMBDA_S3_BUCKET: synvya-user-records-prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # -----------------------------------------------------
    # Checkout & build
    # -----------------------------------------------------
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Setup Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm

    - name: Install deps
      run: |
        npm ci

    # -----------------------------------------------------
    # Auth to AWS via OIDC
    # -----------------------------------------------------
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}   # ❹
        aws-region: ${{ env.AWS_REGION }}

    - name: Generate runtime configuration
      run: |
        # Use dedicated script instead of duplicating logic
        chmod +x scripts/generate-runtime-config.sh
        ./scripts/generate-runtime-config.sh public

    # -----------------------------------------------------
    # Deploy Lambda Functions (only if Lambda code changed)
    # -----------------------------------------------------
    - name: Check if Lambda code changed
      id: lambda-changes
      run: |
        # Check if this is the first commit or if we can diff with previous commit
        if git rev-parse --verify HEAD~1 >/dev/null 2>&1; then
          # We have a previous commit, check for changes
          if git diff --name-only HEAD~1 HEAD | grep -E '^aws-lambda/|^shared/|^scripts/|aws-lambda-infrastructure.yml|cloudfront-security-headers.js'; then
            echo "lambda_changed=true" >> $GITHUB_OUTPUT
          else
            echo "lambda_changed=false" >> $GITHUB_OUTPUT
          fi
        else
          # First commit or shallow clone, deploy Lambda functions
          echo "lambda_changed=true" >> $GITHUB_OUTPUT
          echo "First commit or shallow clone detected, deploying Lambda functions"
        fi

    - name: Make deployment scripts executable
      if: steps.lambda-changes.outputs.lambda_changed == 'true'
      run: chmod +x scripts/*.sh

    - name: Deploy Lambda functions using deployment script
      if: steps.lambda-changes.outputs.lambda_changed == 'true'
      run: ./scripts/deploy-lambda-infrastructure.sh

    - name: Build frontend
      run: |
        npm run build
        # Copy runtime-env.js to the build output
        cp public/runtime-env.js $BUILD_DIR/runtime-env.js

    # -----------------------------------------------------
    # Upload hashed assets (1 year cache) and index.html (60 s)
    # -----------------------------------------------------
    - name: Sync hashed assets to S3
      run: |
        aws s3 sync $BUILD_DIR/ s3://$BUCKET_NAME \
          --exclude "*.html" \
          --cache-control "public,max-age=31536000,immutable"

    - name: Upload index.html with short cache-control
      run: |
        aws s3 cp $BUILD_DIR/index.html s3://$BUCKET_NAME/index.html \
          --cache-control "public,max-age=60"

    # -----------------------------------------------------
    # Bust CloudFront cache for index.html only
    # -----------------------------------------------------
    - name: Invalidate CloudFront cache
      run: |
        # Invalidate both index.html and runtime-env.js to ensure latest configuration is served
        aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/index.html" "/runtime-env.js"

    # Lambda URLs are output by the deployment script