# =========================================================
# Deploy Synvya Client → S3 + CloudFront + Lambda Functions
# =========================================================
name: Deploy client.synvya.com

on:
  push:
    branches: [ main ]
  workflow_dispatch:        # allow manual "Run workflow" button

permissions:
  id-token: write      # <-- allows OIDC token
  contents: read       # <-- allows checkout

concurrency:                # never run two deploys in parallel
  group: deploy-client
  cancel-in-progress: true

env:
  NODE_VERSION: "18"
  BUILD_DIR: dist
  BUCKET_NAME: client-synvya-com               # ❶ S3 bucket
  DISTRIBUTION_ID: E3DPPDWMXK3MAD              # ❂ CloudFront ID
  AWS_REGION: us-east-1                        # ❸ Region for S3 + CLI
  LAMBDA_STACK_NAME: synvya-lambda-infrastructure
  LAMBDA_S3_BUCKET: synvya-subscriptions-prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # -----------------------------------------------------
    # Checkout & build
    # -----------------------------------------------------
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Setup Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm

    - name: Install deps
      run: |
        npm ci

    # -----------------------------------------------------
    # Auth to AWS via OIDC
    # -----------------------------------------------------
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}   # ❹
        aws-region: ${{ env.AWS_REGION }}

    - name: Generate runtime-env.js with correct Lambda URLs
      env:
        STACK_NAME: ${{ env.LAMBDA_STACK_NAME }}
      run: |
        mkdir -p public
        echo "window.runtimeEnv = {" > public/runtime-env.js
        
        # Note: CloudFormation outputs may contain outdated URLs if functions were manually recreated
        # The working URLs (as of the last manual verification) are:
        # - checkSubscriptionUrl: https://si4pgos4rx3nykzya2y5ugcp6a0vwgdj.lambda-url.us-east-1.on.aws/
        # - createZapriteOrderUrl: https://r7sts256fb7qrwouximz3x2q6y0yroyx.lambda-url.us-east-1.on.aws/
        # - paymentWebhookUrl: https://trfdrrplkdsjo3kynxuprpfnre0pxklc.lambda-url.us-east-1.on.aws/
        # - getOrderUrl: https://ynbxffgyxiqun476l2oa27qyma0neved.lambda-url.us-east-1.on.aws/
        # - getUserOrdersUrl: https://msuv6n37lgdw3tlu2ptm5xpsea0rqqoe.lambda-url.us-east-1.on.aws/
        # - checkContactUrl: https://tkrxeipv25uhrl7vea7h2rijgy0duzvo.lambda-url.us-east-1.on.aws/
        
        echo "  checkSubscriptionUrl: \"https://si4pgos4rx3nykzya2y5ugcp6a0vwgdj.lambda-url.us-east-1.on.aws/\"," >> public/runtime-env.js
        echo "  createZapriteOrderUrl: \"https://r7sts256fb7qrwouximz3x2q6y0yroyx.lambda-url.us-east-1.on.aws/\"," >> public/runtime-env.js
        echo "  paymentWebhookUrl: \"https://trfdrrplkdsjo3kynxuprpfnre0pxklc.lambda-url.us-east-1.on.aws/\"," >> public/runtime-env.js
        echo "  getOrderUrl: \"https://ynbxffgyxiqun476l2oa27qyma0neved.lambda-url.us-east-1.on.aws/\"," >> public/runtime-env.js
        echo "  getUserOrdersUrl: \"https://msuv6n37lgdw3tlu2ptm5xpsea0rqqoe.lambda-url.us-east-1.on.aws/\"," >> public/runtime-env.js
        echo "  checkContactUrl: \"https://tkrxeipv25uhrl7vea7h2rijgy0duzvo.lambda-url.us-east-1.on.aws/\"" >> public/runtime-env.js
        echo "};" >> public/runtime-env.js

    # -----------------------------------------------------
    # Deploy Lambda Functions (only if Lambda code changed)
    # -----------------------------------------------------
    - name: Check if Lambda code changed
      id: lambda-changes
      run: |
        # Check if this is the first commit or if we can diff with previous commit
        if git rev-parse --verify HEAD~1 >/dev/null 2>&1; then
          # We have a previous commit, check for changes
          if git diff --name-only HEAD~1 HEAD | grep -E '^aws-lambda/|^scripts/|aws-lambda-infrastructure.yml|cloudfront-security-headers.js'; then
            echo "lambda_changed=true" >> $GITHUB_OUTPUT
          else
            echo "lambda_changed=false" >> $GITHUB_OUTPUT
          fi
        else
          # First commit or shallow clone, deploy Lambda functions
          echo "lambda_changed=true" >> $GITHUB_OUTPUT
          echo "First commit or shallow clone detected, deploying Lambda functions"
        fi

    - name: Make deployment scripts executable
      if: steps.lambda-changes.outputs.lambda_changed == 'true'
      run: chmod +x scripts/*.sh

    - name: Deploy Lambda functions using deployment script
      if: steps.lambda-changes.outputs.lambda_changed == 'true'
      env:
        ZAPRITE_API_KEY: ${{ secrets.ZAPRITE_API_KEY }}
      run: ./scripts/deploy-lambda-infrastructure.sh

    - name: Build frontend
      run: |
        npm run build
        # Copy runtime-env.js to the build output
        cp public/runtime-env.js $BUILD_DIR/runtime-env.js

    # -----------------------------------------------------
    # Upload hashed assets (1 year cache) and index.html (60 s)
    # -----------------------------------------------------
    - name: Sync hashed assets to S3
      run: |
        aws s3 sync $BUILD_DIR/ s3://$BUCKET_NAME \
          --exclude "*.html" \
          --cache-control "public,max-age=31536000,immutable"

    - name: Upload index.html with short cache-control
      run: |
        aws s3 cp $BUILD_DIR/index.html s3://$BUCKET_NAME/index.html \
          --cache-control "public,max-age=60"

    # -----------------------------------------------------
    # Bust CloudFront cache for index.html only
    # -----------------------------------------------------
    - name: Update CloudFront security headers function
      run: |
        # Update the CloudFront function with latest security headers
        aws cloudfront update-function \
          --name synvya-security-headers \
          --function-config Comment="Security headers for client.synvya.com with correct Lambda URLs",Runtime=cloudfront-js-1.0 \
          --function-code fileb://cloudfront-security-headers.js

        # Publish the updated function
        ETAG=$(aws cloudfront describe-function --name synvya-security-headers --query 'ETag' --output text)
        aws cloudfront publish-function --name synvya-security-headers --if-match "$ETAG"

    - name: Invalidate CloudFront cache
      run: |
        # Invalidate both index.html and runtime-env.js to ensure latest configuration is served
        aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/index.html" "/runtime-env.js"

    # Lambda URLs are output by the deployment script